### ISSUE TITLE
Fix javadoc generation on open jdk 11 and 12

### ISSUE THREAD

**Issue by joel-costigliola** [joel-costigliola/assertj-core#1403]
#### Summary

Typical error in travis see https://travis-ci.org/joel-costigliola/assertj-core/jobs/481842510:
```
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-javadoc-plugin:3.0.1:javadoc (default-cli) on project assertj-core: An error has occurred in Javadoc report generation: 
[ERROR] Exit code: 1 - javadoc: error - The code being documented uses modules but the packages defined in https://docs.oracle.com/javase/8/docs/api/ are in the unnamed module.
```

#### Fix

https://issues.apache.org/jira/browse/MJAVADOC-562

**Comment by PascalSchumacher** [comment]
Open JDK issue (https://bugs.openjdk.java.net/browse/JDK-8212233) was reopened and fixed in 12.0.1 and 13. I hope this will be backported to Java 11.

**Comment by PascalSchumacher** [comment]
Open JDK issue is now marked as fixed in Java 11.0.3.

**Comment by joel-costigliola** [comment]
there is hope, we need to wait for travis to use it I guess.

**Comment by hazendaz** [comment]
@joel-costigliola I'm pretty sure this one was fixed by maven with javadoc plugin 3.1.0 and not an issue with java itself.

**Comment by joel-costigliola** [comment]
@hazendaz thanks, looks good. I think I'll bump the version in the parent pom and release it for use in assertj-core.

**Comment by PascalSchumacher** [comment]
Was fixed in https://github.com/joel-costigliola/assertj-maven-parent-pom/commit/9b521bc33ac81b9a809de39c00599a9f928934d8 by the way.

**Comment by joel-costigliola** [comment]
@PascalSchumacher thanks, I forgot about this

**Comment by joel-costigliola** [comment]
Unfortunately the maven-javadoc-plugin 3.10.0 did not fix the issue as per this build https://travis-ci.org/joel-costigliola/assertj-core/builds/543057440.

I'm going to disable the javadoc again for java 11+ projects

**Comment by joel-costigliola** [comment]
Fixed by adding specifying that source is 8 in the maven-javadoc-plugin configuration.

**Comment by csaltos** [comment]
Also adding `<detectJavaApiLink>false</detectJavaApiLink>` to the Maven javadoc pluging configuration section helps

**Comment by hemanthsridhar** [comment]
works with the below configuration.

`<plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-javadoc-plugin</artifactId>
                <version>2.9.1</version>
                <configuration>
                    <source>8</source>
                </configuration>
                <executions>
                    <execution>
                        <id>attach-javadocs</id>
                        <goals>
                            <goal>jar</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>`

**Comment by vsile** [comment]
I add the next code to pom.xml to fix it (compiling Jenkins plugin)
```
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/maven-v4_0_0.xsd">
   ...
    <build>
        <plugins>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-javadoc-plugin</artifactId>
                <version>3.2.0</version>
                <configuration>
                    <source>8</source>
                </configuration>
            </plugin>
        </plugins>
    </build>
    ...
</project>
```

**Comment by jonathanl-telenav** [comment]
> Open JDK issue (https://bugs.openjdk.java.net/browse/JDK-8212233) was reopened and fixed in 12.0.1 and 13. I hope this will be backported to Java 11.

I'm seeing this in 13.0.2+8
