### ISSUE TITLE
Add suppressed exceptions support to AbstractThrowableAssert

### ISSUE THREAD

**Issue by cykl** [joel-costigliola/assertj-core#454]
While `AbstractThrowableAssert` allows to run assertions on the `Throwable` itself, its cause & its root cause; there is no dedicated API for suppressed exceptions. 

I believe it could be useful to check that:

 - No suppressed exception is attached to the Throwable
 - A given Throwable is present in the suppressed exception list (and its usual variants: contains, containsExactly etc.)

**Comment by joel-costigliola** [comment]
I suggest to use `hasNoSuppressedException` for the first requested assertion.

The second request raises an interesting question: how do you compare exception ? 
`contains` assertion relies on `equals` method  elements and exception `equals` is just inherited from `Object` which means that it only compares references.

**Comment by cykl** [comment]
Thanks for the feedback. I indeed noticed that `hasCause` and `hasRootCause` are not using object equality but their own mechanism based on the message and the class. 

I will try to hack something using the same idiom and let you review it.

**Comment by fbiville** [comment]
👍 would like to have at least something to check suppressed exception classes.

**Comment by joel-costigliola** [comment]
done.

**Comment by PascalSchumacher** [comment]
@joel-costigliola : My pull request only added `hasNoSuppressedExceptions` so the `hasSuppressedExceptions` part is still missing.

**Comment by joel-costigliola** [comment]
ok my bad
