### ISSUE TITLE
containsExactly in java 8

### ISSUE THREAD

**Issue by mshoshah** [joel-costigliola/assertj-core#843]
#### Summary
containsExactly fails in java 8. It was working fine in java 7.  When I changed to java 8 all unit tests that use containsExactly started to fail but when I changed from containsExactly to containsOnly everything went fine.

#### Java 8 specific ?

YES. version 1.8.0_111

**Comment by joel-costigliola** [comment]
Can you give a test case that failed so that I can reproduce the problem ?

**Comment by mshoshah** [comment]
The problem occurs when the class lets call it ClassA has its members annotated with @SerializedName and have another class lets call it ClassB that sets the values for ClassA and also returns an array of ClassA. Another class called ClassC that sets the default test data to use them in unittests.

 ClassA obejct1 = ClassC.defaultDataForClassA.build();
 ClassA obejct2 = ClassC.defaultDataForClassA.build();

 obejct2.setId("Id2");

 ClassB.set(obejct1);
 ClassB.set(obejct2);

 List<ClassA> fetchedObjects = ClassB.getAll();
 assertThat(fetchedObjects).containsExactly(obejct1, obejct2);

**Comment by joel-costigliola** [comment]
I can't reproduce the problem if I don't know what ClassA, ClassB and ClassC are.
In order to help you, I need a test case that I can run and that will show the problem.

Moreover a bug in `containsExactly` has been fixed in 2.6.0/3.6.0, what version are you using ?

**Comment by mshoshah** [comment]
It's a company code and I can't  share it on the Internet. We are using 2.3.0 but I changed to 2.6.0 and still get the same problem.

**Comment by PascalSchumacher** [comment]
No need to post the real code. Just share a minimal example  that demonstrates the issue. Thanks in advance!

**Comment by mshoshah** [comment]
Sorry for late reply. The issue was in the Java 8 itself after intensive debugging and troubleshooting.  containsExactlyInAnyOrder works fine but not containsExactly. Java 8 changes the order when fetches the entities from persistence when the class has members annotated with @SerializedName. I don't have any idea why is that. Thanks guys for help.

**Comment by joel-costigliola** [comment]
Thanks for the feedback, does it mean I can close this issue ?

**Comment by mshoshah** [comment]
Yes you can close the issue.
